version: '3.8'

services:
  svelte:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
      - 24678:24678

volumes:
  svelte:
