version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
      - 24678:24678
    command: sh -c "pnpm dev --host 0.0.0.0"

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 6006:6006
    command: sh -c "pnpm storybook"

volumes:
  admin:
  storybook:
