FROM node:lts

RUN apt update
RUN apt install ffmpeg -y
RUN apt-get install g++ build-essential -y

WORKDIR /app

RUN npm i -g pnpm

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY .npmrc ./

RUN pnpm fetch

COPY . .

RUN pnpm install

EXPOSE 5173
EXPOSE 24678
EXPOSE 6006